### ISSUE TITLE
Incorrect biome when inside a cave

### ISSUE THREAD

**Issue by cupang-afk** [pseudoforceyt/PlayerBiomes#2] opened 2023-07-25 08:02 UTC
i am inside a cave on y=8

biome are custom using datapack [terralith](https://www.[planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/](https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/))
![image](https://github.com/pseudoforceyt/PlayerBiomes/assets/66926348/d3312def-7900-4f90-95b6-2f1563fe885b)

**Comment by cupang-afk** [comment] 2023-07-25 13:01
additional info:
when i go a bit deeper like 5-10 blocks, i can recieve the biome name correctly 
![image](https://github.com/pseudoforceyt/PlayerBiomes/assets/66926348/01112802-36ce-4da4-9d89-ee563ff0337a)
but its a bit far off from the original location

**Comment by pseudoforceyt** [comment] 2023-08-01 05:12
Hi, I have originally found this personally during testing for 4.2.0 version. This is confirmed to happen in all previous versions as well.
Sadly I could not fix it because I couldn't find the source of the issue. This plugin handles only the names of the biome which are obtained using the library. I am in talks with the library author to try to find the source of the issue. Will post updates here

**Comment by pseudoforceyt** [comment] 2023-08-01 05:20
@mfnalex

**Comment by pseudoforceyt** [comment] 2023-12-30 05:03
Resolution found; Will be fixed in 5.0.0
All i had to do was divide the coordinates by 4 because apparently biomes are stored only every 4 blocks

**Closed as completed by pseudoforceyt** 2023-12-30 05:03 UTC
Labels: resolved
